language: emacs-lisp
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
# Bootstrap Salt, install the Minion configuration and teach Salt about the
# Travis CI user name
before_install:
  - wget -O - http://bootstrap.saltstack.org | sudo sh
  - sudo install -m 644 -T ./salt/travis.minion /etc/salt/minion
  - sudo salt-call grains.setval travis_user "${USER}"
# Bootstrap the testing environment and install test requirements.  We install
# Ruby tools separately, because
install:
  - sudo salt-call state.highstate
  - make elpa
# Build documentation and run unit tests
script:
  - make -k info test
# Disable Emacs snapshot, because Carton is broken
matrix:
  exclude:
    - env: EMACS=emacs-snapshot